Configure beman.task to export all headers in the task directory (public and implementation headers).
Expected usage (depends on the installation prefix and having beman.execution already installed):

```shell
$ g++-14 -std=c++26 examples/c++now-cancel.cpp -I/opt/beman/beman.task/include/
In file included from /opt/beman/beman.task/include/beman/task/task.hpp:8,
                 from examples/c++now-cancel.cpp:5:
/opt/beman/beman.task/include/beman/task/detail/any_scheduler.hpp:7:10: fatal error: beman/execution/execution.hpp: No such file or directory
    7 | #include <beman/execution/execution.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

$ g++-14 -std=c++26 examples/c++now-cancel.cpp -I/opt/beman/beman.task/include/ -I/opt/beman/beman.execution/include -o c++now-cancel
```